name: Run the qodo-cover action

on:
 workflow_dispatch:     
permissions:
  pull-requests: write # Allows commenting on pull requests
  contents: write # Allows reading and writing files

jobs:
  run-qodo-cover:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
          touch /tmp/report.txt

      - name: qodo-cover
        uses: qodo-ai/qodo-ci/.github/actions/qodo-cover@v0.1.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
          project_language: python
          project_root: .
          code_coverage_report_path: ./coverage.xml
          coverage_type: cobertura
          test_command: "pytest --cov=. --cov-report=xml --cov-report=term" # your test command
          model: gemini/gemini-2.0-flash-lite
          max_iterations: 3
          desired_coverage: 99
          run_each_test_separately: true
          source_folder: ./api/operations
          test_folder: ./api/tests
        env:
          GEMINI_API_KEY: ${{ secrets.GOOGLEAI_API_KEY }}
