name: Qodo Cover

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y gcc git
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install git+https://github.com/qodo-ai/qodo-cover.git
          pip install pytest-cov

      - name: Run qodo cover
        run: |
          cover-agent \
          --code-coverage-report-path "coverage.xml" \
          --test-command "pytest --cov=. --cov-report=xml --cov-report=term" \
          --test-command-dir "api/tests" \
          --coverage-type "cobertura" \
          --desired-coverage 80 \
          --max-iterations 10
